const errorMap: Record<string, string> = {
  unexpected_failure: "Something went wrong. Please try again.",
  validation_failed: "Please double-check your input and try again.",
  bad_json: "There was a problem with your request. Contact support if it keeps happening.",
  email_exists: "That email is already linked to an account.",
  phone_exists: "That phone number is already in use.",
  bad_jwt: "Your session has expired or is invalid.",
  not_admin: "You need admin access to do that.",
  no_authorization: "You're not allowed to do that.",
  user_not_found: "We couldn't find a user with that info.",
  session_not_found: "Session not found. Please sign in again.",
  session_expired: "Your session has expired. Please log in again.",
  refresh_token_not_found: "Couldn’t find a refresh token.",
  refresh_token_already_used: "This refresh token has already been used.",
  flow_state_not_found: "We couldn't find your session. Please try again.",
  flow_state_expired: "Your session has expired. Please try again.",
  signup_disabled: "Sign ups are currently closed.",
  user_banned: "This account has been banned.",
  provider_email_needs_verification: "Please verify your email before continuing.",
  invite_not_found: "This invite doesn’t exist or has expired.",
  bad_oauth_state: "There was a problem with the OAuth login.",
  bad_oauth_callback: "OAuth sign-in failed.",
  oauth_provider_not_supported: "That OAuth provider isn’t supported.",
  unexpected_audience: "Unexpected request source.",
  single_identity_not_deletable: "You can't delete this identity.",
  email_conflict_identity_not_deletable: "This identity can't be deleted due to an email conflict.",
  identity_already_exists: "This identity is already linked.",
  email_provider_disabled: "Email sign-in is currently disabled.",
  phone_provider_disabled: "Phone sign-in is currently disabled.",
  too_many_enrolled_mfa_factors: "You’ve reached the MFA limit.",
  mfa_factor_name_conflict: "An MFA method with that name already exists.",
  mfa_factor_not_found: "We couldn't find that MFA method.",
  mfa_ip_address_mismatch: "MFA failed due to an IP address mismatch.",
  mfa_challenge_expired: "The MFA challenge has expired. Try again.",
  mfa_verification_failed: "MFA verification didn’t work. Try again.",
  mfa_verification_rejected: "MFA verification was rejected.",
  insufficient_aal: "Your session doesn't meet the required security level.",
  captcha_failed: "Captcha failed. Please try again.",
  saml_provider_disabled: "SAML is currently disabled.",
  manual_linking_disabled: "Manual linking is turned off.",
  sms_send_failed: "We couldn’t send the SMS. Try again.",
  email_not_confirmed: "Please confirm your email first.",
  phone_not_confirmed: "Please confirm your phone number first.",
  reauth_nonce_missing: "Reauthentication failed. Try again.",
  saml_relay_state_not_found: "SAML relay info not found.",
  saml_relay_state_expired: "SAML relay session has expired.",
  saml_idp_not_found: "SAML provider not found.",
  saml_assertion_no_user_id: "SAML response missing user ID.",
  saml_assertion_no_email: "SAML response missing email.",
  user_already_exists: "That user already exists.",
  sso_provider_not_found: "SSO provider not found.",
  saml_metadata_fetch_failed: "Couldn’t get SAML metadata.",
  saml_idp_already_exists: "That SAML provider already exists.",
  sso_domain_already_exists: "That SSO domain is already in use.",
  saml_entity_id_mismatch: "SAML entity ID doesn’t match.",
  conflict: "Something in your request caused a conflict.",
  provider_disabled: "This login option is currently disabled.",
  user_sso_managed: "This account is managed by SSO and can’t perform that action.",
  reauthentication_needed: "Please reauthenticate to continue.",
  same_password: "Your new password must be different from the old one.",
  reauthentication_not_valid: "Reauthentication is invalid or expired.",
  otp_expired: "The code has expired. Please try again.",
  otp_disabled: "OTP is disabled on this account.",
  identity_not_found: "We couldn’t find that identity.",
  weak_password: "Your password is too weak. Please choose a stronger one.",
  over_request_rate_limit: "You’re doing that too often. Please slow down.",
  over_email_send_rate_limit: "Too many emails sent. Please wait and try again.",
  over_sms_send_rate_limit: "Too many texts sent. Please wait and try again.",
  bad_code_verifier: "There was a problem verifying your request.",
  anonymous_provider_disabled: "Anonymous sign-in is turned off.",
  hook_timeout: "A server process took too long.",
  hook_timeout_after_retry: "A server process timed out after multiple tries.",
  hook_payload_over_size_limit: "The request was too large.",
  hook_payload_invalid_content_type: "Invalid format in the request.",
  request_timeout: "That took too long. Please try again.",
  mfa_phone_enroll_not_enabled: "Phone MFA setup isn’t enabled.",
  mfa_phone_verify_not_enabled: "Phone MFA isn’t enabled.",
  mfa_totp_enroll_not_enabled: "TOTP MFA setup isn’t enabled.",
  mfa_totp_verify_not_enabled: "TOTP MFA isn’t enabled.",
  mfa_webauthn_enroll_not_enabled: "WebAuthn setup isn’t enabled.",
  mfa_webauthn_verify_not_enabled: "WebAuthn isn’t enabled.",
  mfa_verified_factor_exists: "An MFA method has already been verified.",
  invalid_credentials: "Wrong email or password. Try again.",
  email_address_not_authorized: "That email isn’t allowed to sign in.",
  email_address_invalid: "Please enter a valid email address.",
};


export default function mapSupabaseError(code: string): string {
  return errorMap[code] || `An unknown error occurred (${code})`;
}
